complete -c simrv -f
complete -c simrv -s h -l help -d 'Show help'
complete -c simrv -s m -l image -l memory -r -F -d 'Load an ELF or raw image'
complete -c simrv -l disk -l rootfs -r -F -d 'Attach a VirtIO disk image'
complete -c simrv -l fdt -l dtb -r -F -d 'Load a device tree'
complete -c simrv -l steps -s s -r -d 'Stop after N retired instructions'
complete -c simrv -l harts -l smp -s j -r -d 'Set active hart count'
complete -c simrv -l isa -r -a 'rv32i rv32imac rv32gc rv64i rv64imac rv64gc' -d 'Select a RISC-V ISA'
complete -c simrv -l mode -r -a 'fast detailed cycle-accurate' -d 'Select execution mode'
complete -c simrv -l pipeline -r -a '3stage 5stage' -d 'Select CA pipeline'
complete -c simrv -l bpred -r -a 'none static bimodal gshare tournament' -d 'Select branch predictor'
complete -c simrv -l net -r -a 'user tap socket none' -d 'Select network backend'
complete -c simrv -l soc -l platform -r -a 'virt-pcie virt-mmio rvcomp' -d 'Select SoC preset'
complete -c simrv -l cpu-config -l log-file -l arch-trace -l load-checkpoint -l save-checkpoint -l summary -l events -r -F -d 'File path'
complete -c simrv -l trace-dir -l checkpoint-dir -r -a '(__fish_complete_directories)' -d 'Directory path'
complete -c simrv -l cpu-preset -r -a 'tiny balanced performance' -d 'Select CPU model'
complete -c simrv -l gdb -d 'Start GDB remote debugging'
complete -c simrv -l gdb-port -r -d 'Set GDB server port'
complete -c simrv -l cli -d 'Run headless'
complete -c simrv -l tui -d 'Run interactive TUI'
complete -c simrv -l quiet -s q -d 'Suppress informational logs'
complete -c simrv -l verbose -s v -d 'Enable debug diagnostics'
