/**
 * @file OperationId.hpp
 * @brief Unified RISC-V instruction operation identifiers.
 */
#pragma once

#include <cstddef>
#include <cstdint>

namespace simrv::isa {

enum OperationId : uint16_t {
    /* RV32I */
    LUI,
    AUIPC,
    JAL,
    JALR,
    BEQ,
    BNE,
    BLT,
    BGE,
    BLTU,
    BGEU,
    LB,
    LH,
    LW,
    LD,
    LBU,
    LHU,
    LWU,
    SB,
    SH,
    SW,
    SD,
    ADDI,
    SLTI,
    SLTIU,
    XORI,
    ORI,
    ANDI,
    SLLI,
    SRLI,
    SRAI,
    ADDIW,
    SLLIW,
    SRLIW,
    SRAIW,
    ADD,
    SUB,
    SLL,
    SLT,
    SLTU,
    XOR,
    SRL,
    SRA,
    OR,
    AND,
    ADDW,
    SUBW,
    SLLW,
    SRLW,
    SRAW,
    FENCE,
    FENCE_I,
    ECALL,
    EBREAK,
    CSRRW,
    CSRRS,
    CSRRC,
    CSRRWI,
    CSRRSI,
    CSRRCI,
    /* Privileged */
    URET,
    SRET,
    MRET,
    WFI,
    SFENCE_VMA,
    /* RV32M */
    MUL,
    MULH,
    MULHSU,
    MULHU,
    DIV,
    DIVU,
    REM,
    REMU,
    MULW,
    DIVW,
    DIVUW,
    REMW,
    REMUW,
    /* RV32A */
    LR_W,
    SC_W,
    AMOSWAP_W,
    AMOADD_W,
    AMOXOR_W,
    AMOAND_W,
    AMOOR_W,
    AMOMIN_W,
    AMOMAX_W,
    AMOMINU_W,
    AMOMAXU_W,
    /* RV64A */
    LR_D,
    SC_D,
    AMOSWAP_D,
    AMOADD_D,
    AMOXOR_D,
    AMOAND_D,
    AMOOR_D,
    AMOMIN_D,
    AMOMAX_D,
    AMOMINU_D,
    AMOMAXU_D,
    /* RV32F */
    FLW,
    FSW,
    FMADD_S,
    FMSUB_S,
    FNMADD_S,
    FNMSUB_S,
    FADD_S,
    FSUB_S,
    FMUL_S,
    FDIV_S,
    FSQRT_S,
    FSGNJ_S,
    FSGNJN_S,
    FSGNJX_S,
    FMIN_S,
    FMAX_S,
    FCVT_W_S,
    FCVT_WU_S,
    FMV_X_W,
    FEQ_S,
    FLT_S,
    FLE_S,
    FCLASS_S,
    FCVT_S_W,
    FCVT_S_WU,
    FMV_W_X,
    FCVT_L_S,
    FCVT_LU_S,
    FCVT_S_L,
    FCVT_S_LU,
    /* RV32D */
    FLD,
    FSD,
    FMADD_D,
    FMSUB_D,
    FNMSUB_D,
    FNMADD_D,
    FADD_D,
    FSUB_D,
    FMUL_D,
    FDIV_D,
    FSQRT_D,
    FSGNJ_D,
    FSGNJN_D,
    FSGNJX_D,
    FMIN_D,
    FMAX_D,
    FCVT_S_D,
    FCVT_D_S,
    FEQ_D,
    FLT_D,
    FLE_D,
    FCLASS_D,
    FCVT_W_D,
    FCVT_WU_D,
    FCVT_D_W,
    FCVT_D_WU,
    FMV_X_D,
    FMV_D_X,
    FCVT_L_D,
    FCVT_LU_D,
    FCVT_D_L,
    FCVT_D_LU,
    /* Bitmanip (B) Extension */
    SH1ADD,
    SH2ADD,
    SH3ADD,
    SH1ADD_UW,
    SH2ADD_UW,
    SH3ADD_UW,
    ADD_UW,
    SLLI_UW,
    ANDN,
    ORN,
    XNOR,
    CLZ,
    CTZ,
    CPOP,
    MIN,
    MAX,
    MINU,
    MAXU,
    SEXT_B,
    SEXT_H,
    ZEXT_H,
    ROL,
    ROR,
    RORI,
    CLZW,
    CTZW,
    CPOPW,
    ROLW,
    RORW,
    RORIW,
    CLMUL,
    CLMULH,
    CLMULR,
    BSET,
    BSETI,
    BCLR,
    BCLRI,
    BINV,
    BINVI,
    BEXT,
    BEXTI,
    ORC_B,
    REV8,
    PACK,
    PACKW,
    /* Vector instructions */
    VSETVLI,
    VSETIVLI,
    VSETVL,
    VLE8_V,
    VLE16_V,
    VLE32_V,
    VLE64_V,
    VSE8_V,
    VSE16_V,
    VSE32_V,
    VSE64_V,
    VADD_VV,
    VADD_VX,
    VADD_VI,
    VSUB_VV,
    VSUB_VX,
    VMUL_VV,
    VMUL_VX,
    VDIV_VV,
    VDIV_VX,
    VDIVU_VV,
    VDIVU_VX,
    VAND_VV,
    VAND_VX,
    VAND_VI,
    VOR_VV,
    VOR_VX,
    VOR_VI,
    VXOR_VV,
    VXOR_VX,
    VXOR_VI,
    VSLL_VV,
    VSLL_VX,
    VSLL_VI,
    VSRL_VV,
    VSRL_VX,
    VSRL_VI,
    VSRA_VV,
    VSRA_VX,
    VSRA_VI,
    VMV_V_V,
    VMV_V_X,
    VMV_V_I,
    VMV_X_S,
    VMV_S_X,
    VMSEQ_VV,
    VMSEQ_VX,
    VMSEQ_VI,
    VMSNE_VV,
    VMSNE_VX,
    VMSNE_VI,
    VMSLT_VV,
    VMSLT_VX,
    VMSLTU_VV,
    VMSLTU_VX,
    VMSLE_VV,
    VMSLE_VX,
    VMSLE_VI,
    VMSLEU_VV,
    VMSLEU_VX,
    VMSLEU_VI,
    VMSGT_VX,
    VMSGT_VI,
    VMSGTU_VX,
    VMSGTU_VI,
    VMERGE_VVM,
    VMERGE_VXM,
    VMERGE_VIM,
    VMACC_VV,
    VMACC_VX,
    VMADD_VV,
    VMADD_VX,
    VNMSAC_VV,
    VNMSAC_VX,
    VNSUB_VV,
    VNSUB_VX,
    VWMACCU_VV,
    VWMACCU_VX,
    VWMACC_VV,
    VWMACC_VX,
    VWMACCUS_VX,
    VWMACCSU_VV,
    VWMACCSU_VX,
    VMIN_VV,
    VMIN_VX,
    VMINU_VV,
    VMINU_VX,
    VMAX_VV,
    VMAX_VX,
    VMAXU_VV,
    VMAXU_VX,
    VLSE8_V,
    VLSE16_V,
    VLSE32_V,
    VLSE64_V,
    VSSE8_V,
    VSSE16_V,
    VSSE32_V,
    VSSE64_V,
    VLUXEI8_V,
    VLUXEI16_V,
    VLUXEI32_V,
    VLUXEI64_V,
    VLOXEI8_V,
    VLOXEI16_V,
    VLOXEI32_V,
    VLOXEI64_V,
    VSUXEI8_V,
    VSUXEI16_V,
    VSUXEI32_V,
    VSUXEI64_V,
    VSOXEI8_V,
    VSOXEI16_V,
    VSOXEI32_V,
    VSOXEI64_V,
    VID_V,
    VFMACC_VV,
    VFMACC_VF,
    VREDSUM_VS,
    VWMUL_VV,
    VWMUL_VX,
    VNCLIP_WV,
    VNCLIP_WX,
    VNCLIP_WI,
    VNCLIPU_WV,
    VNCLIPU_WX,
    VNCLIPU_WI,
    VNSRL_WV,
    VNSRL_WX,
    VNSRL_WI,
    VNSRA_WV,
    VNSRA_WX,
    VNSRA_WI,
    VSLIDE1UP_VX,
    VSLIDE1DOWN_VX,
    VFADD_VV,
    VFADD_VF,
    VRSUB_VX,
    VRSUB_VI,
    VSADD_VV,
    VSADD_VX,
    VSADD_VI,
    VSADDU_VV,
    VSADDU_VX,
    VSADDU_VI,
    VSBC_VVM,
    VSBC_VXM,
    VSEXT_VF2,
    VSEXT_VF4,
    VSEXT_VF8,
    VZEXT_VF2,
    VZEXT_VF4,
    VZEXT_VF8,
    VSLIDEDOWN_VX,
    VSLIDEDOWN_VI,
    VSLIDEUP_VX,
    VSLIDEUP_VI,
    VSMUL_VV,
    VSMUL_VX,
    VSSRA_VV,
    VSSRA_VX,
    VSSRA_VI,
    VSSRL_VV,
    VSSRL_VX,
    VSSRL_VI,
    VSSUB_VV,
    VSSUB_VX,
    VSSUBU_VV,
    VSSUBU_VX,
    VWADD_VV,
    VWADD_VX,
    VWADD_WV,
    VWADD_WX,
    VWADDU_VV,
    VWADDU_VX,
    VWADDU_WV,
    VWADDU_WX,
    VWSUB_VV,
    VWSUB_VX,
    VWSUB_WV,
    VWSUB_WX,
    VWSUBU_VV,
    VWSUBU_VX,
    VWSUBU_WV,
    VWSUBU_WX,
    VWMULU_VV,
    VWMULU_VX,
    VWMULSU_VV,
    VWMULSU_VX,
    VWREDSUM_VS,
    VWREDSUMU_VS,
    /* Whole register moves */
    VMV1R_V,
    VMV2R_V,
    VMV4R_V,
    VMV8R_V,
    /* Whole register loads */
    VL1RE8_V,
    VL1RE16_V,
    VL1RE32_V,
    VL1RE64_V,
    VL2RE8_V,
    VL2RE16_V,
    VL2RE32_V,
    VL2RE64_V,
    VL4RE8_V,
    VL4RE16_V,
    VL4RE32_V,
    VL4RE64_V,
    VL8RE8_V,
    VL8RE16_V,
    VL8RE32_V,
    VL8RE64_V,
    /* Whole register stores */
    VS1R_V,
    VS2R_V,
    VS4R_V,
    VS8R_V,
    /* Add with carry / subtract with borrow */
    VADC_VVM,
    VADC_VXM,
    VADC_VIM,
    VMADC_VV,
    VMADC_VX,
    VMADC_VI,
    VMADC_VVM,
    VMADC_VXM,
    VMADC_VIM,
    VMSBC_VV,
    VMSBC_VX,
    VMSBC_VVM,
    VMSBC_VXM,
    /* Mask instructions */
    VMSBF_M,
    VMSIF_M,
    VMSOF_M,
    VFIRST_M,
    VCPOP_M,
    VIOTA_M,
    VCOMPRESS_VM,
    /* Vector bitmanip Zvbb/Zvbc */
    VANDN_VV,
    VANDN_VX,
    VROL_VV,
    VROL_VX,
    VROR_VV,
    VROR_VX,
    VROR_VI,
    VCLZ_V,
    VCTZ_V,
    VCPOP_V,
    VBREV_V,
    VBREV8_V,
    VREV8_V,
    VCLMUL_VV,
    VCLMUL_VX,
    VCLMULH_VV,
    VCLMULH_VX,
    VMAND_MM,
    VMNAND_MM,
    VMANDN_MM,
    VMOR_MM,
    VMNOR_MM,
    VMORN_MM,
    VMXOR_MM,
    VMXNOR_MM,
    VFMV_F_S,
    VFMV_S_F,
    VFMERGE_VFM,
    VWSLL_VV,
    VWSLL_VX,
    VWSLL_VI,
    VCHECK,
    /* Others */
    UNKNOWN,
    OperationIdCount
};

/// @brief Start of base RV32I integer instruction IDs
constexpr OperationId kOpRangeRv32iBegin = LUI;
/// @brief End of base RV32I integer instruction IDs
constexpr OperationId kOpRangeRv32iEnd = CSRRCI;

/// @brief Start of privileged instruction IDs
constexpr OperationId kOpRangePrivBegin = URET;
/// @brief End of privileged instruction IDs
constexpr OperationId kOpRangePrivEnd = SFENCE_VMA;

/// @brief Start of RV32M/RV64M multiply-divide instruction IDs
constexpr OperationId kOpRangeRv32mBegin = MUL;
/// @brief End of RV32M/RV64M multiply-divide instruction IDs
constexpr OperationId kOpRangeRv32mEnd = REMU;

/// @brief Start of RV32A atomic instruction IDs
constexpr OperationId kOpRangeRv32aBegin = LR_W;
/// @brief End of RV32A atomic instruction IDs
constexpr OperationId kOpRangeRv32aEnd = AMOMAXU_W;

/// @brief Start of RV32F single-precision float instruction IDs
constexpr OperationId kOpRangeRv32fBegin = FLW;
/// @brief End of RV32F single-precision float instruction IDs
constexpr OperationId kOpRangeRv32fEnd = FCVT_S_LU;

/// @brief Start of RV32D double-precision float instruction IDs
constexpr OperationId kOpRangeRv32dBegin = FLD;
/// @brief End of RV32D double-precision float instruction IDs
constexpr OperationId kOpRangeRv32dEnd = FCVT_D_LU;

/// @brief Unified count of all valid simulator operations
constexpr size_t kOperationIdCount = static_cast<size_t>(OperationIdCount);

}  // namespace simrv::isa
