# Toolchain for fully static x86-64 Linux release binaries.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(MUSL_TOOLCHAIN_ROOT "$ENV{MUSL_TOOLCHAIN_ROOT}" CACHE PATH
    "Root of the x86_64-linux-musl cross toolchain")
if(NOT MUSL_TOOLCHAIN_ROOT)
  message(FATAL_ERROR "MUSL_TOOLCHAIN_ROOT must point to an x86_64-linux-musl toolchain")
endif()
set(_musl_bin "${MUSL_TOOLCHAIN_ROOT}/bin")
set(CMAKE_C_COMPILER "${_musl_bin}/x86_64-linux-musl-gcc" CACHE FILEPATH "musl C compiler")
set(CMAKE_CXX_COMPILER "${_musl_bin}/x86_64-linux-musl-g++" CACHE FILEPATH "musl C++ compiler")
set(CMAKE_AR "${_musl_bin}/x86_64-linux-musl-ar" CACHE FILEPATH "musl archiver")
set(CMAKE_RANLIB "${_musl_bin}/x86_64-linux-musl-ranlib" CACHE FILEPATH "musl ranlib")
set(CMAKE_STRIP "${_musl_bin}/x86_64-linux-musl-strip" CACHE FILEPATH "musl strip")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-static")
set(CMAKE_FIND_ROOT_PATH "${MUSL_TOOLCHAIN_ROOT}/x86_64-linux-musl")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
