.TH "BlockRequestHeader" 3 "Version 1.3.7" "SimCore/RISC-V" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockRequestHeader
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBioprio\fP"
.br
.ti -1c
.RI "uint64_t \fBsector_num\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SimCore/RISC-V from the source code\&.
