.TH "Microcn" 3 "Version 1.3.7" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Microcn \- The \fBMicrocn\fP class represents the I/O controller (micro-controller)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <machine\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (char *filename)"
.br
.RI "Initializes the I/O controller\&. "
.ti -1c
.RI "int \fBexec\fP ()"
.br
.RI "Executes the I/O controller program\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t * \fBcmem\fP"
.br
.ti -1c
.RI "uint8_t * \fBmmem\fP"
.br
.ti -1c
.RI "\fBQueueState\fP * \fBcons_queue\fP"
.br
.ti -1c
.RI "\fBQueueState\fP * \fBdisk_queue\fP"
.br
.ti -1c
.RI "uint8_t \fBcons_fifo\fP"
.br
.ti -1c
.RI "uint8_t \fBfifo_en\fP"
.br
.ti -1c
.RI "uint8_t * \fBdisk\fP"
.br
.ti -1c
.RI "uint32_t \fBMode\fP"
.br
.ti -1c
.RI "uint32_t \fBQnum\fP"
.br
.ti -1c
.RI "uint32_t \fBQsel\fP"
.br
.ti -1c
.RI "uint32_t \fBpc\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBcpc\fP"
.br
.ti -1c
.RI "uint32_t \fBreg\fP [32]"
.br
.ti -1c
.RI "uint32_t \fBicnt\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBr_ir\fP"
.br
.ti -1c
.RI "uint32_t \fBr_opcode\fP"
.br
.ti -1c
.RI "uint32_t \fBr_rd\fP"
.br
.ti -1c
.RI "uint32_t \fBr_rs1\fP"
.br
.ti -1c
.RI "uint32_t \fBr_rs2\fP"
.br
.ti -1c
.RI "uint32_t \fBr_funct3\fP"
.br
.ti -1c
.RI "uint32_t \fBr_funct5\fP"
.br
.ti -1c
.RI "uint32_t \fBr_funct7\fP"
.br
.ti -1c
.RI "uint32_t \fBr_funct12\fP"
.br
.ti -1c
.RI "uint32_t \fBr_imm\fP"
.br
.ti -1c
.RI "uint32_t \fBr_rrs1\fP"
.br
.ti -1c
.RI "uint32_t \fBr_rrs2\fP"
.br
.ti -1c
.RI "uint32_t \fBr_tkn\fP"
.br
.ti -1c
.RI "uint32_t \fBr_jmp_pc\fP"
.br
.ti -1c
.RI "uint32_t \fBr_mem_addr\fP"
.br
.ti -1c
.RI "uint32_t \fBr_wb_data\fP"
.br
.ti -1c
.RI "uint32_t \fBr_wb_data_csr\fP"
.br
.ti -1c
.RI "uint32_t \fBr_mem_rdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBMicrocn\fP class represents the I/O controller (micro-controller)\&. 
.SH "Member Function Documentation"
.PP 
.SS "int Microcn::exec ()"

.PP
Executes the I/O controller program\&. 
.PP
\fBReturns\fP
.RS 4
0 if successful, otherwise an error code\&. 
.RE
.PP

.SS "void Microcn::init (char * filename)"

.PP
Initializes the I/O controller\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP The filename of the I/O controller program binary\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
