.TH "QueueState" 3 "Version 1.3.7" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueueState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBReady\fP"
.br
.ti -1c
.RI "uint32_t \fBNotify\fP"
.br
.ti -1c
.RI "uint32_t \fBDescLow\fP"
.br
.ti -1c
.RI "uint32_t \fBDescHigh\fP"
.br
.ti -1c
.RI "uint32_t \fBAvailLow\fP"
.br
.ti -1c
.RI "uint32_t \fBAvailHigh\fP"
.br
.ti -1c
.RI "uint32_t \fBUsedLow\fP"
.br
.ti -1c
.RI "uint32_t \fBUsedHigh\fP"
.br
.ti -1c
.RI "uint32_t \fBlast_avail_idx\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
