.TH "TLBEntry" 3 "Version 1.3.7" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TLBEntry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBv_addr\fP"
.br
.ti -1c
.RI "uint32_t \fBp_addr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
