foreach(required_var SIMRV_BIN SIMRV_FW_PAYLOAD SIMRV_DISK_IMAGE SIMRV_DTB)
  if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
    message(FATAL_ERROR "${required_var} is required")
  endif()
endforeach()

foreach(required_file "${SIMRV_BIN}" "${SIMRV_FW_PAYLOAD}" "${SIMRV_DISK_IMAGE}" "${SIMRV_DTB}")
  if(NOT EXISTS "${required_file}")
    message(FATAL_ERROR "Required Linux run artifact does not exist: ${required_file}")
  endif()
endforeach()

set(command "${SIMRV_BIN}" -m "${SIMRV_FW_PAYLOAD}" -D "${SIMRV_DISK_IMAGE}" -f "${SIMRV_DTB}")
if(SIMRV_TUI)
  list(APPEND command -u)
endif()
execute_process(COMMAND ${command} RESULT_VARIABLE run_result)
if(NOT run_result EQUAL 0)
  message(FATAL_ERROR "SimRV Linux run failed with status ${run_result}")
endif()
